version: 0.0
os: linux

files:
  - source: target/todo-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
