version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven
      - yum install -y maven

  build:
    commands:
      - mvn clean package

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**
